GET http://localhost:3333/clientes HTTP/1.1

###

POST http://localhost:3333/clientes HTTP/1.1
content-type: application/json

{
      "nome": "",
      "email": "leandro@email.com",
      "genero": "masculino",
      "telefone": "2122225555",
      "endereco": "Rua 1, 123",
      "cidade": "Rio de Janeiro",
      "estado": "Rio de Janeiro"
}

###

PATCH http://localhost:3333/clientes/c0032ac8-7a3d-4a7a-9c31-78b26d0b1430 HTTP/1.1
content-type: application/json

{
      "nome": "Leandro Ferreira de Jesus"
}

###

DELETE http://localhost:3333/clientes/c0032ac8-7a3d-4a7a-9c31-78b26d0b1430 HTTP/1.1


###

GET http://localhost:3333/clientes/c0032ac8-7a3d-4a7a-9c31-78b26d0b1430 HTTP/1.1

###